### ISSUE TITLE
[FEATURE] AAS Web UI should have the Technical Data Viewer like Package Explorer.

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-aas-web-ui#12]
**Describe the solution you'd like**
In the AAS Web UI it would be nice to be able to view the Technical Data in a tabular form the same way it’s shown in the Package Explorer.

**Describe alternatives you've considered**
I do not know if there is already a plugin for this.

**Comment by aaronzi** [comment]
Hi @JS-Aibel,

the AAS Web UI already has a plugin for this. It's implemented here: https://github.com/eclipse-basyx/basyx-aas-web-ui/blob/main/aas-web-ui/src/components/SubmodelPlugins/TechnicalData.vue

It is automatically shown in the `visualization` window when you click on a technical data submodel that has the following semanticId:

```
https://admin-shell.io/ZVEI/TechnicalData/Submodel/1/2
```

The plugin looks like this:

![Image](https://github.com/user-attachments/assets/6a1c322d-cb8f-409a-83c0-1ad13ff6dad4)

It is not using a table structure since the submodel could potentially be deeply nested. THis is why we decided to implement it like this:

![Image](https://github.com/user-attachments/assets/ca218caf-4094-48ff-82d6-ec7a2c405e04)

If you have a good alternative to how this plugin could look (for example using a table that somehow supports nesting), please feel free to open a new ticket describing this in detail.

Best regards,
Aaron
