### ISSUE TITLE
[FEATURE] "Jumping" to an AAS should reveal the AAS in the AAS list

### ISSUE THREAD

**Issue by de-ich** [eclipse-basyx/basyx-aas-web-ui#86]
**Is your feature request related to a problem? Please describe.**
When "jumping" to an AAS (e.g. either via clicking on an element in a BOM or via using a direct link like `<endpoint>/aas-ui/?aas=<aas-id>`), the AAS is selected in the AAS list (on the left) and the submodels are shown in the submodel list. However, when there are a lot of AASes in the AAS list, it is possible that the highlighted AAS is not in the viewport of the user. As there is no other indicator anywhere on the page that shows e.g. the name of the currently displayed AAS, it is not possible to recognize which AAS is actually opened (unless one scrolls through the list of AASes in the AAS list until one finds the highlighted one).

**Describe the solution you'd like**
When "jumping" to an AAS, the the AAS list should be automatically scrolled until the selected AAS is in the users viewport. Additionally, there might be another indicator of the currently selected AAS showing e.g. its name. This could for example be placed at the top of the submodel list.

**Comment by aaronzi** [comment]
Hello @de-ich,

You have a good point. Automatic scrolling may not be trivial, but it is definitely possible. Showing the name of the AAS at the top of the submodel list is easy to implement, and in fact we already did it for the mobile version. We will add this to the desktop version as well. I will move this ticket to our backlog so that it can be implemented in the next few weeks.

![Image](https://github.com/user-attachments/assets/def6bf18-f0f0-4708-b536-892471db6657)

**Comment by seicke** [comment]
In view of #96 it would be nice if the automatic scrolling (after jumping) can beimplemented in that way, that the selected AAS is shown at the top of the list
